version: '3.7'

services:
  bot:
    container_name: birthday-bot
    platform: linux/amd64
    restart: always
    build:
      dockerfile: Dockerfile
  nginx:
    container_name: nginx
    platform: linux/amd64
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - bot